import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar/Navbar";
import { Lexend } from "next/font/google";

// Configuring Lexend font with specific weights, styles, and subsets
const lexend = Lexend({
  weight: ["400", "500", "600"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

// Metadata for the Next.js application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component that wraps the entire application
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <div className="bg-seashell">
          {/* Navbar component */}
          <Navbar />

          {/* Main content container with styling */}
          <div className="max-w-6xl mx-auto px-6 bg-white-smoke">
            {/* Rendering children components */}
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
